AWSTemplateFormatVersion: '2010-09-09'
##############################################################################
# Parameters
##############################################################################
Parameters:
  AmiID:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'
Resources:
  Example:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: !Ref AmiID
      InstanceType: "t2.micro"
      Tags:
        - Key: Name
          Value: "Helloworld"
